language: bash
sudo: true
services:
  - docker

before_install:
  - docker info
  - docker version

  - echo "==> Build with Docker ..."
  - docker build -f tests/Dockerfile.ubuntu1204 -t zabbix-agent:ubuntu1204  . | tee build_result.ubuntu1204
  - docker build -f tests/Dockerfile.ubuntu1404 -t zabbix-agent:ubuntu1404  . | tee build_result.ubuntu1404
  - docker build -f tests/Dockerfile.ubuntu1604 -t zabbix-agent:ubuntu1604  . | tee build_result.ubuntu1604
  - docker build -f tests/Dockerfile.debian8    -t zabbix-agent:debian8     . | tee build_result.debian8
  - docker build -f tests/Dockerfile.centos6    -t zabbix-agent:centos6     . | tee build_result.centos6

script:
  - echo "==> Run Test case ..."
  - grep '00:00:00 zabbix_agentd' build_result.ubuntu1204
  - grep '00:00:00 zabbix_agentd' build_result.ubuntu1404
  - grep '00:00:00 zabbix_agentd' build_result.ubuntu1604
  - grep '00:00:00 zabbix_agentd' build_result.debian8
  - grep '00:00:00 zabbix_agentd' build_result.centos6

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: AJFBeD10vrRblz1n6eiSDWn8MCok97Do7daWdq8Sjek1k4Ib6C+9PZVpxsQno8Otr/5yWdv3WZlF2oR9LAFWX7cs/PkGDQVTQ0+L0wpl0YbLx1yxJCkI9n8QVb31yICVygZbWmfgSk+bz6fxs88KwxQqVyN9CczdPUtD002WOULdsvi3SeHO3DP+bVPmuofUeavwHocbw86GgiSqp3+tXLQcp5JYR9eEzdjwfOZxbU8RQQEjwdiWI9s4c0RnEYfmBb8Hx4nEY1cbf/4dnKENf5j3fIbu4Y5fDMTLw9/ITqGeVaQOKWCDXwRahmaY7FPX/i59BSITIm/e0R0+OM2CoW9dwbN5uuZw5U+k+Y7/VhZ9zglBxo9vSkX9OCwrfDxvmt0z23eCOrDGIapRI358qQS5jOY6AXYx0oUy9Jr5fHkfaiYzTVnRLcv8VGGVf9LktqvymjCvzxGX1WuU6Sfz0KZgcl7dUmF1lI8K3isoaWHz3QlVOXReN7cGf0YJWtAeWLAdnQRPHRMvv/BZFWEdpKOOsbu/H/+d9PPlSDpg7N8FQC6NrI6XpyaCwGxAgOrRoVcOyNmY/7X7Rc1QF/Rq/4WhPis9a3XtOErU1QN2VJF6D+wyQeARu3PTeqzqQi3XoIlqTWHBMDnftkK1PQEQfYYfL5mEjMnz8eSw9niu7ps=

env:
  global:
    secure: OVTDGcfPBwBWNdhQaTh2ERUUJhpo1+lkKbHdzbpJeo+qUtOhLHixCZr3BEphgZlSDmkG3hxjZYI5u2vG8UHrHtZ9dfQik5sWIllHeF/y0pfdIKw+dov/Qyvk8m1BfX4WdMymtPkEDmnsLaMazgcNezZYZBwKqybdt7Hno+9YzfNqE15nM8MlNrpDdxDbIgjHOKn1mdZbiz8+3mDiHM0hBUTME+yWR6MEJpISAvWGMFESOLdme/t4yLHMl6NxWQz49RDCHWQjnl3sPVyA9bgUrxKXELDlj73KDor0mZC4D/u9SSVbaKaFtnb1RzBwBfTkpiDLPwN4hkL+Qg/E5qFluMMPoMf+wDyPz0kSXuSKhAgzsta+DCAs2GUkfFNBdwNj9inFegzzyPQkKT7IZGRX/BGRB2PmV+YvBk0+akThUNNKAO2YahrMCEdKN7U3hD8hW8XSoSgbzJ2kxaVfRiKGlsAuXRkADPYTKLMwwALbuhc0oEcq1nptyhbQKOy9W2rCBHu3J3jal0m63ulYJdnWCb/dtnAolXqm5PiAB5LLiFRmIWvmp/qfzjuMThCxPTcxSxmjKOUdgLxkbNWvS1xPqRRDSR9cwr6g59j807TrdzHPIJfNv21frQ8cQNgPLlNsaH+aQy6/m4Ebelyba4TGh14JR2G8woYnyN2xFzDh6Qw=
