language: bash
sudo: true
services:
  - docker

before_install:
  - docker info
  - docker version
  
  - echo "==> Build with Docker ..."
  
  # Ubuntu
  - docker build -f tests/Dockerfile.ubuntu1204  -t zabbix-agent:ubuntu1204 . | tee build_result.ubuntu1204
  - docker build -f tests/Dockerfile.ubuntu1404  -t zabbix-agent:ubuntu1404 . | tee build_result.ubuntu1404
  - docker build -f tests/Dockerfile.ubuntu1604  -t zabbix-agent:ubuntu1604 . | tee build_result.ubuntu1604
  
  # Debian
  #- docker build -f tests/Dockerfile.debian7 -t zabbix-agent:debian7 .    | tee build_result.debian7
  - docker build -f tests/Dockerfile.debian8 -t zabbix-agent:debian8 .    | tee build_result.debian8
  
  # CentOS
  - docker build -f tests/Dockerfile.centos6 -t zabbix-agent:centos6 .    | tee build_result.centos6
  #- docker build -f test/Dockerfile.centos7 -t zabbix-agent:centos7 .    | tee build_result.centos7
  
script:
  - echo "==> Run Test case ..."
  
  - grep '00:00:00 zabbix_agentd' build_result.ubuntu1204
  - grep '00:00:00 zabbix_agentd' build_result.ubuntu1404
  - grep '00:00:00 zabbix_agentd' build_result.ubuntu1604

  #- grep '00:00:00 zabbix_agentd' build_result.debian7
  - grep '00:00:00 zabbix_agentd' build_result.debian8

  - grep '00:00:00 zabbix_agentd' build_result.centos6
  #- grep '00:00:00 zabbix_agentd' build_result.centos7

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  hipchat:
    secure: "DTnXg490xbC3HB3Qs/8aSDSRlrVUBWrDzywuo6+PJrTrQFZbAbn1Xeey9wmibkIB6AigZew+EeBTcmIkactb6zH8cTwOBAaZIAiU2SgMjCBkMXOPblvCd9DToL8ul5/jkwu8ZfV91ncrujczajZDPA1qaKhU3LKqpCVCHIxptRyX2FRsiGS1/2IJSWM/GdVWHzRr4OdYcLixqPlC40iQf6sDlCJAlGmkNSGyMDJ9nOlPKH0fRXW+DBSUMcbYFYO7v3AfDlBibWcaCohhVfaMeYt0BGuQ0cDaxMPPqJbvBySHB04OGFbjFCnQgQe9Q/e7SlUctoKumzloIwcoJOnKtZpHuayXYegRSbUuvVhm0E2a3OHjeuenKdjddF1lOAuUyBal3Jlqy1yIwLafW6lCNaR2+xyJ/tcL2Ds/SSTFnvzxZH1j43acJ59mkFjrA6TQUt81sOG4nlFjHOoD+DriCY1tc6WVP3IltjZUyQBvOrg08DtnTHCJYMG6Yep9hg9y4WO7Hi/3eWiA4z8vYNzOBOz2xVKlqyWTTELwSp04PsnZHxmRInoXdPYK0Jmyh3qNtslcw4l5oHb0htFwyqCPBWbjb0wm/5OrIVcnFXYt9k3/uDOCzz9QsPhulg5Ei+159gNMn4w9djzLVK4IUkzBf/X4PwwH7h56WccHsCGchsc="

