#!/usr/bin/env ansible-playbook
# vim:ft=ansible:

---
- name: play 'zabbix-agent.ansible.role/setup.yml'
  hosts: all
  #become: true

  #roles:
  #  - { role: chusiang.vim-and-vi-mode, tags: ["development"] }

  vars_files:
    - defaults/main.yml

  tasks:
    - name: include main task
      include: tasks/main.yml

    - name: check process
      shell: ps -A | grep zabbix-agent
      register: zabbix-agent_process

    - name: print process
      debug:
        msg: "{{ zabbix-agent_process.stdout_lines }}"

  handlers:
    - name: include main handler
      include: handlers/main.yml

