#!/usr/bin/env ansible-playbook

---

- name: delegate to 'apt' system for installation
  include: use-apt.yml
  when: ansible_pkg_mgr == "apt"

- name: delegate to 'yum' system for installation
  include: use-yum.yml
  when: ansible_pkg_mgr == "yum"

- name: print version
  debug:
    msg: "Zabbix-Agent Version: {{ package_version.stdout }}"

- name: enable/start the zabbix-agent service
  service:
    name: zabbix-agent
    enabled: yes
    state: started

- name: modify configure
  become: yes
  template: src=templates/zabbix_agentd.conf.j2 dest=/etc/zabbix/zabbix_agentd.conf
  notify: restart zabbix-agent

# vim:ft=ansible:
