#!/usr/bin/env ansible-playbook

---

- name: install zabbix-release
  become: true
  yum: name={{ zabbix_release_rpm }} state=present

- name: install zabbix-agent
  become: true
  yum: name=zabbix-agent update_cache=yes state=present

- name: check version
  command: rpm -q zabbix-agent
  register: package_version

- name: print version
  debug:
    msg: "Zabbix-Agent Version: {{ package_version.stdout }}"

# use same path like debian system.
- name: create '/etc/zabbix/zabbix_agentd.conf.d/' directory
  become: true
  file:
    path: /etc/zabbix/zabbix_agentd.conf.d/
    state: directory

- name: create '/var/log/zabbix-agent/' directory
  become: true
  file:
    path: /var/log/zabbix-agent/
    group: zabbix
    state: directory
    mode: 0775

# Remove the old zabbix-agent logs.
- name: delete '/var/log/zabbix/zabbix_agentd.log' file
  become: true
  file:
    path: /var/log/zabbix/zabbix_agentd.log
    state: absent

- name: delete '/var/log/zabbix/' directory
  become: true
  file:
    path: /var/log/zabbix/
    state: absent

# vim:ft=ansible:
